name: TechSuda
favicon: null
layout_spectrum: 0.4461890181992203
typography_spectrum: 0.8405157416127622
title: TSNetwork
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6106687565334141
  lightness: 0.4375
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
