name: TechSuda
favicon: null
layout_spectrum: 0.75557
typography_spectrum: 0.61831
title: TechSuda News
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#494949'
    - '#c3a89d'
    - '#08090b'
    - '#ff7558'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
